name: HACS Validation

on:
  push:
    branches:
      - main
      - beta
  pull_request:
  workflow_dispatch:

jobs:
  hacs_validation:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Home Assistant Core Integration Validation (Hassfest)
        uses: home-assistant/actions/hassfest@master
